
alias ls='ls --color=auto'
alias l='ls -lF --color=auto'
alias ll='ls -laF --color=auto'
alias lst='ls -ltrF --color=auto'
alias la='ls -laF --color=auto'

alias so='source'
alias sob='source ~/.bash_profile'
alias v='vim'
alias vi='vim'
alias vb='vim ~/.bash_profile'
alias c='cdr'
alias h='history'
alias mv='mv -i'
alias cp='cp -i'
alias rm='rm -i'
alias mkdir='mkdir -p'
alias ..='c ../'
alias back='pushd'
alias diff='diff -U1'
alias gs='git status'

alias ..='cd ../'
alias ...='cd ../..'
alias ....='cd ../../..'

