
if [[ "$OSTYPE" == "linux-gnu" ]]; then
  # Linux
  source ~/.config/bash/alias_common.inc
  source ~/.config/bash/alias_linux.inc
else
  # Mac
  # source .bashrc
  if [ -f ~/.bashrc ]; then
    source ~/.bashrc
  fi
  if [ -f ~/.bash_profile ]; then
    source ~/.bash_profile
  fi
fi

export EDITORP=vim #エディタをvimに設定
export LANG=ja_JP.UTF-8 #文字コードをUTF-8に設定
setopt IGNOREEOF # Ctrl+Dでログアウトしてしまうことを防ぐ

# 色を使用
autoload -Uz colors
colors

# プロンプトを2行で表示、時刻を表示
PROMPT="%(?.%{${fg[green]}%}.%{${fg[red]}%})%n${reset_color}@${fg[blue]}%m${reset_color}(%*%) %~
  %# "

# エイリアス
alias soz='source ~/.zshrc'
alias h='history -df'

bindkey -e
bindkey '^[[Z' reverse-menu-complete
autoload -U compinit; compinit
setopt auto_cd
setopt auto_pushd
setopt pushd_ignore_dups
setopt extended_glob
setopt hist_reduce_blanks
setopt hist_no_store
# setopt hist_ignore_all_dups
# setopt hist_ignore_space
zstyle ':completion:*:default' menu select=1
WORDCHARS='*?_-.[]~=&;!#$%^(){}<>'

# history
HISTSIZE=1000
SAVEHIST=10000
setopt extended_history #ヒストリに実行時間も保存
setopt hist_ignore_dups #直前と同じコマンドはヒストリに追加しない
export HISTFILE=${HOME}/.zsh_history

# git設定
RPROMPT="%{${fg[blue]}%}[%~]%{${reset_color}%}"
autoload -Uz vcs_info
setopt prompt_subst
zstyle ':vcs_info:git:*' check-for-changes true
zstyle ':vcs_info:git:*' stagedstr "%F{yellow}!"
zstyle ':vcs_info:git:*' unstagedstr "%F{red}+"
zstyle ':vcs_info:*' formats "%F{green}%c%u[%b]%f"
zstyle ':vcs_info:*' actionformats '[%b|%a]'
precmd () { vcs_info }
RPROMPT=$RPROMPT'${vcs_info_msg_0_}'
