alias c='cdr'
alias h='history'
alias mv='mv -i'
alias cp='cp -i'
alias rm='rm -i'
alias mkdir='mkdir -p'
alias ..='c ../'
alias back='pushd'
alias diff='diff -U1'

alias so='source'
alias sob='source ~/.bash_profile'

alias ..='cd ../'
alias ...='cd ../..'
alias ....='cd ../../..'

alias v='vim'
alias vi='vim'
alias vb='vim ~/.bash_profile'

alias gs='git status'
alias gd='git diff'
alias gdd='git diff --cached'
alias gl='git log'
alias gla="git log --graph --all --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
alias ga='git add'
alias gc='git commit'
alias gsh='git push'
alias gll='git pull'

alias tailf='tail -f'

